version: "3.3"
services:
  db:
    image: postgres:14-alpine
    container_name: udemy_clone
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=hello
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=udemy_database
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    volumes:
    - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5432"
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@domain.de
      PGADMIN_DEFAULT_PASSWORD: pgadmin
volumes:
  db_data: